/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteOmarArgs } from "./DeleteOmarArgs";
import { OmarFindManyArgs } from "./OmarFindManyArgs";
import { OmarFindUniqueArgs } from "./OmarFindUniqueArgs";
import { Omar } from "./Omar";
import { OmarService } from "../omar.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Omar)
export class OmarResolverBase {
  constructor(
    protected readonly service: OmarService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Omar",
    action: "read",
    possession: "any",
  })
  async _omarsMeta(
    @graphql.Args() args: OmarFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Omar])
  @nestAccessControl.UseRoles({
    resource: "Omar",
    action: "read",
    possession: "any",
  })
  async omars(@graphql.Args() args: OmarFindManyArgs): Promise<Omar[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Omar, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Omar",
    action: "read",
    possession: "own",
  })
  async omar(@graphql.Args() args: OmarFindUniqueArgs): Promise<Omar | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Omar)
  @nestAccessControl.UseRoles({
    resource: "Omar",
    action: "delete",
    possession: "any",
  })
  async deleteOmar(@graphql.Args() args: DeleteOmarArgs): Promise<Omar | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
