/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CampaignDetailUpdateManyWithoutUsersInput } from "./CampaignDetailUpdateManyWithoutUsersInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { CampaignUpdateManyWithoutUsersInput } from "./CampaignUpdateManyWithoutUsersInput";
import { CompanyDetailUpdateManyWithoutUsersInput } from "./CompanyDetailUpdateManyWithoutUsersInput";
import { IsJSONValue } from "@app/custom-validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { StatisticUpdateManyWithoutUsersInput } from "./StatisticUpdateManyWithoutUsersInput";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: () => CampaignDetailUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => CampaignDetailUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => CampaignDetailUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  campaignDetails?: CampaignDetailUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => CampaignUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => CampaignUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => CampaignUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  campaigns?: CampaignUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => CompanyDetailUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => CompanyDetailUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => CompanyDetailUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  companyDetails?: CompanyDetailUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  roles?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => StatisticUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => StatisticUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => StatisticUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  statistics?: StatisticUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;
}

export { UserUpdateInput as UserUpdateInput };
