/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BoughtDealUpdateManyWithoutUsersInput } from "./BoughtDealUpdateManyWithoutUsersInput";
import { ValidateNested, IsOptional, IsString, IsJSON } from "class-validator";
import { Type } from "class-transformer";
import { CampaignDetailUpdateManyWithoutUsersInput } from "./CampaignDetailUpdateManyWithoutUsersInput";
import { CampaignUpdateManyWithoutUsersInput } from "./CampaignUpdateManyWithoutUsersInput";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: () => BoughtDealUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => BoughtDealUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => BoughtDealUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  boughtDeals?: BoughtDealUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => CampaignDetailUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => CampaignDetailUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => CampaignDetailUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  campaignDetails?: CampaignDetailUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => CampaignUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => CampaignUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => CampaignUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  campaigns?: CampaignUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
  })
  @IsJSON()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  roles?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;
}

export { UserUpdateInput as UserUpdateInput };
