/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CampaignDetailListRelationFilter } from "../../campaignDetail/base/CampaignDetailListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { CampaignListRelationFilter } from "../../campaign/base/CampaignListRelationFilter";
import { CompanyRegistrationListRelationFilter } from "../../companyRegistration/base/CompanyRegistrationListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { StatisticListRelationFilter } from "../../statistic/base/StatisticListRelationFilter";

@InputType()
class UserWhereInput {
  @ApiProperty({
    required: false,
    type: () => CampaignDetailListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CampaignDetailListRelationFilter)
  @IsOptional()
  @Field(() => CampaignDetailListRelationFilter, {
    nullable: true,
  })
  campaignDetails?: CampaignDetailListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => CampaignListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CampaignListRelationFilter)
  @IsOptional()
  @Field(() => CampaignListRelationFilter, {
    nullable: true,
  })
  campaigns?: CampaignListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => CompanyRegistrationListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CompanyRegistrationListRelationFilter)
  @IsOptional()
  @Field(() => CompanyRegistrationListRelationFilter, {
    nullable: true,
  })
  companyDetails?: CompanyRegistrationListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  firstName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  lastName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => StatisticListRelationFilter,
  })
  @ValidateNested()
  @Type(() => StatisticListRelationFilter)
  @IsOptional()
  @Field(() => StatisticListRelationFilter, {
    nullable: true,
  })
  statistics?: StatisticListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  username?: StringFilter;
}

export { UserWhereInput as UserWhereInput };
