/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CampaignDetailService } from "../campaignDetail.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CampaignDetailCreateInput } from "./CampaignDetailCreateInput";
import { CampaignDetailWhereInput } from "./CampaignDetailWhereInput";
import { CampaignDetailWhereUniqueInput } from "./CampaignDetailWhereUniqueInput";
import { CampaignDetailFindManyArgs } from "./CampaignDetailFindManyArgs";
import { CampaignDetailUpdateInput } from "./CampaignDetailUpdateInput";
import { CampaignDetail } from "./CampaignDetail";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CampaignDetailControllerBase {
  constructor(
    protected readonly service: CampaignDetailService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CampaignDetail })
  @nestAccessControl.UseRoles({
    resource: "CampaignDetail",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(
    @common.Body() data: CampaignDetailCreateInput
  ): Promise<CampaignDetail> {
    return await this.service.create({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        bought: true,
        createdAt: true,
        description: true,
        hoursMinutesSeconds: true,
        id: true,
        interactionRate: true,
        redeemed: true,
        saved: true,
        totalSales: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        websiteTraffic: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [CampaignDetail] })
  @ApiNestedQuery(CampaignDetailFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CampaignDetail",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<CampaignDetail[]> {
    const args = plainToClass(CampaignDetailFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        bought: true,
        createdAt: true,
        description: true,
        hoursMinutesSeconds: true,
        id: true,
        interactionRate: true,
        redeemed: true,
        saved: true,
        totalSales: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        websiteTraffic: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CampaignDetail })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CampaignDetail",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: CampaignDetailWhereUniqueInput
  ): Promise<CampaignDetail | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        bought: true,
        createdAt: true,
        description: true,
        hoursMinutesSeconds: true,
        id: true,
        interactionRate: true,
        redeemed: true,
        saved: true,
        totalSales: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        websiteTraffic: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CampaignDetail })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CampaignDetail",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: CampaignDetailWhereUniqueInput,
    @common.Body() data: CampaignDetailUpdateInput
  ): Promise<CampaignDetail | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          bought: true,
          createdAt: true,
          description: true,
          hoursMinutesSeconds: true,
          id: true,
          interactionRate: true,
          redeemed: true,
          saved: true,
          totalSales: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          websiteTraffic: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CampaignDetail })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CampaignDetail",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: CampaignDetailWhereUniqueInput
  ): Promise<CampaignDetail | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          bought: true,
          createdAt: true,
          description: true,
          hoursMinutesSeconds: true,
          id: true,
          interactionRate: true,
          redeemed: true,
          saved: true,
          totalSales: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          websiteTraffic: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
