/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CompanyRegistrationService } from "../companyRegistration.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CompanyRegistrationCreateInput } from "./CompanyRegistrationCreateInput";
import { CompanyRegistrationWhereInput } from "./CompanyRegistrationWhereInput";
import { CompanyRegistrationWhereUniqueInput } from "./CompanyRegistrationWhereUniqueInput";
import { CompanyRegistrationFindManyArgs } from "./CompanyRegistrationFindManyArgs";
import { CompanyRegistrationUpdateInput } from "./CompanyRegistrationUpdateInput";
import { CompanyRegistration } from "./CompanyRegistration";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CompanyRegistrationControllerBase {
  constructor(
    protected readonly service: CompanyRegistrationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CompanyRegistration })
  @nestAccessControl.UseRoles({
    resource: "CompanyRegistration",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(
    @common.Body() data: CompanyRegistrationCreateInput
  ): Promise<CompanyRegistration> {
    return await this.service.create({
      data: {
        ...data,

        user: {
          connect: data.user,
        },
      },
      select: {
        approvalStatus: true,
        businessAddress: true,
        businessCategory: true,
        businessEmail: true,
        businessPhoneNumber: true,
        companyName: true,
        companyUrl: true,
        createdAt: true,
        cvrNumber: true,
        id: true,
        logo: true,
        shortIntroductionToTheCompany: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [CompanyRegistration] })
  @ApiNestedQuery(CompanyRegistrationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CompanyRegistration",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(
    @common.Req() request: Request
  ): Promise<CompanyRegistration[]> {
    const args = plainToClass(CompanyRegistrationFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        approvalStatus: true,
        businessAddress: true,
        businessCategory: true,
        businessEmail: true,
        businessPhoneNumber: true,
        companyName: true,
        companyUrl: true,
        createdAt: true,
        cvrNumber: true,
        id: true,
        logo: true,
        shortIntroductionToTheCompany: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CompanyRegistration })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CompanyRegistration",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: CompanyRegistrationWhereUniqueInput
  ): Promise<CompanyRegistration | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        approvalStatus: true,
        businessAddress: true,
        businessCategory: true,
        businessEmail: true,
        businessPhoneNumber: true,
        companyName: true,
        companyUrl: true,
        createdAt: true,
        cvrNumber: true,
        id: true,
        logo: true,
        shortIntroductionToTheCompany: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CompanyRegistration })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CompanyRegistration",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: CompanyRegistrationWhereUniqueInput,
    @common.Body() data: CompanyRegistrationUpdateInput
  ): Promise<CompanyRegistration | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          user: {
            connect: data.user,
          },
        },
        select: {
          approvalStatus: true,
          businessAddress: true,
          businessCategory: true,
          businessEmail: true,
          businessPhoneNumber: true,
          companyName: true,
          companyUrl: true,
          createdAt: true,
          cvrNumber: true,
          id: true,
          logo: true,
          shortIntroductionToTheCompany: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CompanyRegistration })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CompanyRegistration",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: CompanyRegistrationWhereUniqueInput
  ): Promise<CompanyRegistration | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          approvalStatus: true,
          businessAddress: true,
          businessCategory: true,
          businessEmail: true,
          businessPhoneNumber: true,
          companyName: true,
          companyUrl: true,
          createdAt: true,
          cvrNumber: true,
          id: true,
          logo: true,
          shortIntroductionToTheCompany: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
